application: helloworld
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: src/main/webapp/index.html
  upload: src/main/webapp/index.html
- url: /static
  static_dir: src/main/webapp/static
- url: /.*
  script: _go_app