application: teak-listener-691
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: src/main/webapp/index.html
  upload: src/main/webapp/index.html
- url: /login
  static_files: src/main/webapp/login.html
  upload: src/main/webapp/login.html
- url: /add-user
  static_files: src/main/webapp/add-user.html
  upload: src/main/webapp/add-party.html
- url: /static
  static_dir: src/main/webapp
- url: /.*
  script: _go_app